const DATA = [
  {
    "sl": 1,
    "name": "হিমাংশু কুমার ডালিম",
    "name_en": "Himangshu Kumar Dalim",
    "nid": "730637009757",
    "father": "কুমুদ রঞ্জন রায়",
    "mother": "শেবা রানী রায়",
    "dob": "1980-12-01",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637009757",
    "gender": "পুরুষ",
    "occupation": "বেসরকারী চাকুরী",
    "pdf": "pdfs/730637009757.pdf"
  },
  {
    "sl": 2,
    "name": "কেশব চন্দ্র রায়",
    "name_en": "Keshab Chandra Roy",
    "nid": "730637011297",
    "father": "তারক চন্দ্র রায়",
    "mother": "বাসন্তী রানী রায়",
    "dob": "1965-06-01",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011297",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011297.pdf"
  },
  {
    "sl": 3,
    "name": "পরিতোষ চন্দ্র রায়",
    "name_en": "Paritosh Chandra Roy",
    "nid": "730637010973",
    "father": "সুনীল চন্দ্র রায়",
    "mother": "অঞ্জলী রানী",
    "dob": "1988-05-11",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637010973",
    "gender": "পুরুষ",
    "occupation": "শ্রমিক",
    "pdf": "pdfs/730637010973.pdf"
  },
  {
    "sl": 4,
    "name": "ব্রজেন্দ্র নাথ রায়",
    "name_en": "Brojendra Nath Roy",
    "nid": "730637011275",
    "father": "মহিন্দ্র নাথ রায়",
    "mother": "চারু বালা রায়",
    "dob": "1969-04-01",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011275",
    "gender": "পুরুষ",
    "occupation": "দিনমজুর",
    "pdf": "pdfs/730637011275.pdf"
  },
  {
    "sl": 5,
    "name": "দুলাল চন্দ্র রায়",
    "name_en": "Dulal Chandra Roy",
    "nid": "730637011280",
    "father": "কুলোদা মোহন রায়",
    "mother": "প্রভা রানী রায়",
    "dob": "1988-05-10",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011280",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011280.pdf"
  },
  {
    "sl": 6,
    "name": "আদেশ চন্দ্র রায়",
    "name_en": "Adesh Chandra Roy",
    "nid": "730637011282",
    "father": "তপন কুমার রায়",
    "mother": "ঝর্ণা রানী রায়",
    "dob": "1999-08-09",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011282",
    "gender": "পুরুষ",
    "occupation": "দিনমজুর",
    "pdf": "pdfs/730637011282.pdf"
  },
  {
    "sl": 7,
    "name": "ভোলা নাথ রায়",
    "name_en": "Bhola Nath Roy",
    "nid": "730637011285",
    "father": "উপিন চন্দ্র রায়",
    "mother": "সুরো বালা",
    "dob": "1988-05-25",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011285",
    "gender": "পুরুষ",
    "occupation": "কৃষक",
    "pdf": "pdfs/730637011285.pdf"
  },
  {
    "sl": 8,
    "name": "অশ্বনী কুমার রায়",
    "name_en": "Ashwani Kumar Roy",
    "nid": "730637011291",
    "father": "নগেন্দ্র নাথ রায়",
    "mother": "রাধীকা রানী রায়",
    "dob": "1962-03-05",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011291",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011291.pdf"
  },
  {
    "sl": 9,
    "name": "দ্বারকা নাথ রায়",
    "name_en": "Dwarka Nath Roy",
    "nid": "730637011292",
    "father": "কৃষ্ণ কান্ত রায়",
    "mother": "বিনো বালা রায়",
    "dob": "1962-03-05",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011292",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011292.pdf"
  },
  {
    "sl": 10,
    "name": "মুকন্দ কুমার রায়",
    "name_en": "Mukunda Kumar Roy",
    "nid": "730637011293",
    "father": "চন্দ্র শেখর কুমার রায়",
    "mother": "ছবি বালা রায়",
    "dob": "1981-01-01",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011293",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011293.pdf"
  },
  {
    "sl": 11,
    "name": "পরিমল চন্দ্র রায়",
    "name_en": "Parimal Chandra Roy",
    "nid": "730637011294",
    "father": "অনিল চন্দ্র রায়",
    "mother": "সন্ধ্যা রানী রায়",
    "dob": "1988-05-05",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637011294",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637011294.pdf"
  },
  {
    "sl": 12,
    "name": "মিথুন চন্দ্র রায়",
    "name_en": "Mithun Chandra Roy",
    "nid": "730637996268",
    "father": "দক্ষদা মোহন রায়",
    "mother": "গৌরি রায়",
    "dob": "1987-02-04",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637996268",
    "gender": "পুরুষ",
    "occupation": "কৃষक",
    "pdf": "pdfs/730637996268.pdf"
  },
  {
    "sl": 13,
    "name": "সুবাস চন্দ্র রায়",
    "name_en": "Subas Chandra Roy",
    "nid": "730637996450",
    "father": "হরিশ চন্দ্র রায়",
    "mother": "সমো বালা",
    "dob": "1980-04-01",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637996450",
    "gender": "পুরুষ",
    "occupation": "কৃষক",
    "pdf": "pdfs/730637996450.pdf"
  },
  {
    "sl": 15,
    "name": "পদার চন্দ্র রায়",
    "name_en": "Podar Chandra Roy",
    "nid": "730637996246",
    "father": "কুষ্ট কান্ত রায়",
    "mother": "বিনোদিনী",
    "dob": "1959-02-05",
    "village": "আরাজী চাঁদখানা",
    "union": "গড়াগ্ৰাম",
    "post": "খামাত গড়াগ্ৰাম",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "phone": "01738782255",
    "voter_no": "730637996246",
    "gender": "পুরুষ",
    "occupation": "দিনমজুর",
    "pdf": "pdfs/730637996246.pdf"
  }
];

// E-Porcha & Khatian Boi Database
const KHATIAN_DATA = [
  {
    "sl": 1,
    "khatian_no": "২৬",
    "dag_no": "৪২",
    "mouza": "উত্তর চাঁদখানা",
    "jl_no": "১২",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "division": "রংপুর",
    "owner": "হিমাংশু কুমার ডালিম",
    "father": "কুমুদ রঞ্জন রায়",
    "land_type": "ভিটা / ধানী জমি (এস এ খতিয়ান)",
    "area": "০.৫২ একর (৫২ শতাংশ)",
    "pdf": "pdfs/khatian-26.pdf"
  },
  {
    "sl": 2,
    "khatian_no": "১১২",
    "dag_no": "৪৫",
    "mouza": "উত্তর চাঁদখানা",
    "jl_no": "১২",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "division": "রংপুর",
    "owner": "হিমাংশু কুমার ডালিম",
    "father": "কুমুদ রঞ্জন রায়",
    "land_type": "ভিটা",
    "area": "০.১৫ একর (১৫ শতাংশ)",
    "pdf": "pdfs/khatian-112.pdf"
  },
  {
    "sl": 3,
    "khatian_no": "২৫৪",
    "dag_no": "১০৮",
    "mouza": "দক্ষিণ চাঁদখানা",
    "jl_no": "১৪",
    "upazila": "কিশোরগঞ্জ",
    "district": "নীলফামারী",
    "division": "রংপুর",
    "owner": "মোঃ শাহআলম হাওলাদার",
    "father": "মৃত আঃ ছত্তার হাওলাদার",
    "land_type": "ধানী জমি",
    "area": "০.৩৮ একর (৩৮ শতাংশ)",
    "pdf": "pdfs/khatian-254.pdf"
  },
  {
    "sl": 4,
    "khatian_no": "৭১",
    "dag_no": "২৩",
    "mouza": "উত্তর চাঁদখানা",
    "jl_no": "১২",
    "upazila": "کিশোরগঞ্জ",
    "district": "নীলফামারী",
    "division": "রংপুর",
    "owner": "মোঃ জসিম উদ্দিন",
    "father": "মোঃ আব্দুল করিম",
    "land_type": "ডাঙ্গা",
    "area": "০.০৯ একর (৯ শতাংশ)",
    "pdf": "pdfs/khatian-71.pdf"
  }
];
